// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_ScreenStart
void ui_ScreenStart_screen_init(void);
void ui_event_ScreenStart(lv_event_t * e);
extern lv_obj_t * ui_ScreenStart;
extern lv_obj_t * ui_Label1;
// SCREEN: ui_ScreenMain
void ui_ScreenMain_screen_init(void);
extern lv_obj_t * ui_ScreenMain;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_MiSansBold16);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
