/*
 * @Author: generated by assistant
 * @Description: 简易音频播放器，接收16位单声道PCM样本，放入环形缓冲，由播放任务写入I2S
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

esp_err_t audio_player_init(size_t ring_bytes, size_t frame_samples);
void      audio_player_deinit(void);
esp_err_t audio_player_start(void);
esp_err_t audio_player_stop(void);
bool      audio_player_running(void);

// 投递PCM到播放器（16位单声道，sample_count为样本数）
esp_err_t audio_player_feed_pcm(const int16_t *pcm, size_t sample_count);

#ifdef __cplusplus
}
#endif


