/*
 * @Author: generated by assistant
 * @Description: 按键语音输入模块，处理boot0按键的按下/松开，控制录音和事件发送
 */
#pragma once

#include <stdint.h>
#include <stdbool.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

#define BUTTON_GPIO_NUM GPIO_NUM_0  ///< boot0引脚作为按键

/**
 * @brief 初始化按键语音输入模块
 * @return esp_err_t 
 */
esp_err_t button_voice_init(void);

/**
 * @brief 反初始化按键语音输入模块
 */
void button_voice_deinit(void);

/**
 * @brief 检查是否正在录音
 * @return true 正在录音，false 未录音
 */
bool button_voice_is_recording(void);

#ifdef __cplusplus
}
#endif
